### ISSUE TITLE
Is this the repository of BinForce as presented on FEAST 2017?

### ISSUE THREAD

**Issue by mewmew** [utds3lab/binforce#1]
If so, thanks for sharing your work with the community. It would be very interesting to take a closer look, and thus awaiting your release of the source code with anticipation.

Happy regards,
Robin

https://tc.gtisc.gatech.edu/feast17/papers/short-lin.pdf

**Comment by utds3lab** [comment]
Yes, this repository was initially intended to be the location for our rewriter, but we have renamed the framework since FEAST.  It is now called Multiverse, and the source is available right now in a different repository: https://github.com/utds3lab/multiverse

This is the same rewriter described at FEAST, just with a different name.

We also published a paper about Multiverse in NDSS 2018, which can be found here: http://wp.internetsociety.org/ndss/wp-content/uploads/sites/25/2018/02/ndss2018_05A-4_Bauman_paper.pdf

**Comment by mewmew** [comment]
Thanks a lot @utds3lab! Will take a closer look
